name: Deploy

on:
  push:
    branches: [master]

env:
  EM_VERSION: 3.1.18
  EM_CACHE_FOLDER: 'emsdk-cache'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master


      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 1.6.4

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
          
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Update nimble
        run: nimble update -y

      - name: Build game
        run: nimble -d:release -d:emscripten build

      - name: Bundle files
        run: zip site.zip index.* _headers

      - name: Deploy site
        run: |
          curl -H "Content-Type: application/zip" \
             -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
             --data-binary "@site.zip" \
             https://api.netlify.com/api/v1/sites/eloquent-cranachan-5b1f6f.netlify.app/deploys
